name: ChromaTag
version: '1.2.2'
main: com.jellypudding.chromaTag.ChromaTag
api-version: '1.21'
description: "Customise player name colours for chat, the tab list, and above their heads."
author: AlphaAlex115
website: www.minecraftoffline.net
loadbefore: [OfflineStore, DiscordRelay]
commands:
  chromatag:
    description: "Set and manage player name colors"
    usage: "/chromatag <color|reset> [player]"
    aliases: [ct]
    permission: chromatag.use
    permission-message: "You don't have permission to use ChromaTag."
permissions:
  chromatag.use:
    description: "Allows using ChromaTag commands"
    default: op
  chromatag.set.self:
    description: "Allows setting own name color"
    default: op
  chromatag.set.other:
    description: "Allows setting other players' name colors"
    default: op
  chromatag.reset.self:
    description: "Allows resetting own name color to default"
    default: op
  chromatag.reset.other:
    description: "Allows resetting other players' name colors to default"
    default: op
